package admin

import (
	"fmt"
	"net/http"
	"os"
	"strings"

	"github.com/andrewbakercloudscale/claude-burst/internal/claudesettings"
	"github.com/andrewbakercloudscale/claude-burst/internal/config"
	"github.com/andrewbakercloudscale/claude-burst/internal/tlsca"
)

// This file implements the dashboard's "Revert to normal Claude" button.
//
// It used to revert IN PROCESS: remove ANTHROPIC_BASE_URL from settings.json,
// drop the local CA from ~/.claude/certs, and then merely *print* the sudo
// command for the machine-wide half. That failed for real on 2026-09-07 and
// the failure is worth writing down, because the button did exactly what it
// was written to do and still left the Mac broken:
//
//   - /etc/hosts pointed api.anthropic.com at 127.0.0.1 while the pf rdr
//     443->7777 had gone missing, so EVERY process on this Mac got
//     "connection refused" for Anthropic.
//   - Clicking Revert removed the CA first and left the hosts entry, moving
//     the machine from "broken" to the state interceptActive itself calls
//     "worse than not intercepting".
//   - The one thing that would have fixed it -- scripts/rollback.sh -- was
//     printed as text and had to be found and run by hand.
//
// A revert button that cannot undo the widest-blast-radius change it is
// offered for is not a revert button. So this now does what Install already
// does: generate a script and open it in Terminal, where there is a human to
// answer the sudo prompt and watch every command. The script runs
// scripts/rollback.sh -- the same one that actually recovered the machine --
// rather than a second implementation of it, because two copies of a recovery
// path is how one of them ends up wrong.

type revertResponse struct {
	// Script is where the generated script was written, so a run whose
	// Terminal window never appeared still leaves something runnable behind.
	Script string `json:"script,omitempty"`
	// Steps is only populated by the in-process fallback below. The normal
	// path performs nothing itself; rollback.sh narrates its own work in the
	// Terminal window.
	Steps       []string `json:"steps,omitempty"`
	NeedsRoot   bool     `json:"needs_root"`
	RootCommand string   `json:"root_command,omitempty"`
	Warning     string   `json:"warning,omitempty"`
	Detail      string   `json:"detail,omitempty"`
}

// handleRevert puts Claude Code -- and this Mac -- back on the stock Anthropic
// endpoint by running scripts/rollback.sh in a Terminal window.
func (s *Server) handleRevert(w http.ResponseWriter, r *http.Request) {
	cfg, err := config.Load()
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	dir, ok := s.scriptsDir()
	if !ok {
		// No scripts/ to run. Do the half that needs no root rather than
		// nothing at all, and say plainly which half is left.
		s.revertInProcess(w, cfg)
		return
	}

	path, err := writeGeneratedScript("revert", revertScript(dir))
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	resp := revertResponse{Script: path, NeedsRoot: true}
	if err := launchTerminal(path); err != nil {
		resp.Detail = fmt.Sprintf("could not open Terminal (%v). The rollback script is ready -- run it yourself:\n%s", err, path)
		writeJSON(w, resp)
		return
	}
	resp.Detail = "A Terminal window is now running scripts/rollback.sh. It asks for your password (sudo) " +
		"because /etc/hosts, the pf rule and the System-keychain CA trust are machine-wide, and it verifies " +
		"that api.anthropic.com is reachable directly before it says it is done. Watch it to the end, then restart Claude Code."
	writeJSON(w, resp)
}

// revertScript wraps scripts/rollback.sh rather than reimplementing it. The
// wrapper exists for two things the script itself cannot do: state up front
// what is about to change (the window is the only place the user sees this,
// since the browser confirm is gone by then), and hold the window open on
// exit -- rollback.sh exits 2 when it cannot verify direct connectivity, and
// that is precisely the run whose output must not vanish.
func revertScript(scriptsDir string) string {
	var b strings.Builder
	fmt.Fprintf(&b, `#!/bin/zsh
# Generated by the Claude Burst admin UI. Rewritten on every click of Revert --
# edit scripts/rollback.sh in the repo, not this file.
set -uo pipefail

SCRIPTS=%s

echo "== Claude Burst: revert to normal Claude =="
echo
echo "This runs scripts/rollback.sh, which undoes EVERY part of the intercept,"
echo "widest blast radius first:"
echo "  1. /etc/hosts redirect + the pf rdr rule            (needs sudo)"
echo "  2. the local CA's trust in the System keychain      (needs sudo)"
echo "  3. ~/.claude/settings.json and config.json, from the last backup"
echo "  4. stops the gateway LaunchAgent"
echo "  5. verifies api.anthropic.com is reachable DIRECTLY before saying done"
echo
echo "Step 3 restores settings.json wholesale from the most recent backup, so"
echo "changes made to it since that backup are rolled back too."
echo

if [[ ! -x "$SCRIPTS/rollback.sh" ]]; then
  echo "cannot find $SCRIPTS/rollback.sh -- nothing has been changed" >&2
  echo
  read -k 1 "?Press any key to close this window..."
  exit 1
fi

"$SCRIPTS/rollback.sh"
rc=$?
echo
if (( rc == 0 )); then
  echo "== revert complete -- restart Claude Code =="
else
  echo "== rollback.sh exited $rc: something is STILL in the way ==" >&2
  echo "Read its output above; it names the exact checks to run." >&2
fi
echo
read -k 1 "?Press any key to close this window..."
exit $rc
`, shellQuote(scriptsDir))
	return b.String()
}

// revertInProcess is the fallback for an install with no scripts/ directory
// beside the binary. It is the old behavior, kept only because doing the
// no-root half beats doing nothing -- and it reports the machine-wide half as
// an outstanding warning rather than letting the button read as complete.
func (s *Server) revertInProcess(w http.ResponseWriter, cfg config.Config) {
	out := revertResponse{}

	p, err := claudesettings.Path()
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	root, err := claudesettings.Read(p)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if claudesettings.ClearBaseURL(root, cfg.Listen) {
		if err := claudesettings.Write(p, root); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		out.Steps = append(out.Steps, "removed ANTHROPIC_BASE_URL from settings.json")
	} else {
		out.Steps = append(out.Steps, "settings.json already had no gateway URL")
	}

	// Ordering matters and is the opposite of what it looks like. Dropping the
	// CA while an /etc/hosts redirect is still installed does not soften the
	// breakage, it deepens it: requests still arrive here and now fail TLS.
	// So the CA only comes out once nothing is being redirected at us.
	hostsActive := false
	if h, err := os.ReadFile("/etc/hosts"); err == nil {
		hostsActive = config.HostsRedirectActive(h, cfg.Intercept.Host)
	}
	switch {
	case hostsActive:
		out.Steps = append(out.Steps, "left the local CA in place: the /etc/hosts redirect is still installed, and removing the CA first would break TLS for traffic that is still being sent here")
	case cfg.Intercept.CABundle != "":
		if b, err := os.ReadFile(cfg.Intercept.CABundle); err == nil && tlsca.HasBlock(string(b)) {
			if err := tlsca.RemoveFromBundle(cfg.Intercept.CABundle); err != nil {
				http.Error(w, err.Error(), http.StatusInternalServerError)
				return
			}
			out.Steps = append(out.Steps, "removed the local CA from the trust bundle (other certificates untouched)")
		}
	}

	if hostsActive {
		out.NeedsRoot = true
		out.RootCommand = "sudo " + s.rootHelper + " remove"
		out.Warning = "An /etc/hosts redirect is still installed, and this build has no scripts/ directory to run the full rollback from. " +
			"Until you run the command above, traffic to " + cfg.Intercept.Host +
			" from every process on this Mac still goes to the gateway."
	}
	out.Steps = append(out.Steps, "restart Claude Code for this to take effect")
	writeJSON(w, out)
}
